---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-ceph-block
